spring:
  application:
    name: gateway-service

  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        allowed-origins: "http://localhost:4201"
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
        allowed-headers: "*"
        allow-credentials: true

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
